import React from "react";

export default () => {
  return (
    <table>
      <tr>
        <th>ID</th>
        <th>Class</th>
      </tr>
      <tr>
        <td>1</td>
        <td>Barbarian</td>
      </tr>
      <tr>
        <td>2</td>
        <td>Bard</td>
      </tr>
      <tr>
        <td>3</td>
        <td>Cleric</td>
      </tr>
      <tr>
        <td>4</td>
        <td>Druid</td>
      </tr>
      <tr>
        <td>5</td>
        <td>Fighter</td>
      </tr>
      <tr>
        <td>6</td>
        <td>Monk</td>
      </tr>
      <tr>
        <td>7</td>
        <td>Paladin</td>
      </tr>
      <tr>
        <td>8</td>
        <td>Ranger</td>
      </tr>
      <tr>
        <td>9</td>
        <td>Rogue</td>
      </tr>
      <tr>
        <td>10</td>
        <td>Sorcerer</td>
      </tr>
      <tr>
        <td>11</td>
        <td>Wizard</td>
      </tr>
    </table>
  );
};
